export default {
  INIT_START: 'INIT_START',
  INIT_FETCH_START: 'INIT_FETCH_START',
  INIT_IMAGE_SAVE_START: 'INIT_IMAGE_SAVE_START',
  INIT_WEBTOON_SAVE_START: 'INIT_WEBTOON_SAVE_START',
  INIT_SUCCESS: 'INIT_SUCCESS',
  INIT_FAIL: 'INIT_FAIL',
}
