export default {
  SITE_CHANGED: 'SITE_CHANGED',
  WEBTOON_SELECTED: 'WEBTOON_SELECTED',
  EPISODE_SELECTED: 'EPISODE_SELECTED',
  WEBTOONS_UPDATED: 'WEBTOONS_UPDATED',
  EPISODE_UPDATED: 'EPISODE_UPDATED',
  TOON_IMAGES_UPDATED: 'TOON_IMAGES_UPDATED',
}
