export const SITE_UPDATE = 'SITE_UPDATE'
export const SITE_UPDATE_SUCCESS = 'SITE_UPDATE_SUCCESS'
export const WEBTOON_SELECTED = 'WEBTOON_SELECTED'
export const EPISODE_SELECTED = 'EPISODE_SELECTED'
export const WEBTOON_UPDATED = 'WEBTOON_UPDATED'
export const EPISODE_UPDATED = 'EPISODE_UPDATED'

export const GET_EPISODES_DB = 'GET_EPISODES_DB'
export const GET_EPISODES_DB_SUCCESS = 'GET_EPISODES_DB_SUCCESS'
export const GET_EPISODES_DB_FAIL = 'GET_EPISODES_DB_FAIL'

export const GET_EPISODES_API = 'GET_EPISODES_API'
export const GET_EPISODES_API_FAIL = 'GET_EPISODES_API_FAIL'

export const GET_TOON_IMAGES_API = 'GET_TOON_IMAGES_API'
export const GET_TOON_IMAGES_API_SUCCESS = 'GET_TOON_IMAGES_SUCCESS'
export const GET_TOON_IMAGES_API_FAIL = 'GET_TOON_IMAGES_FAIL'

export const TOON_IMAGES_UPDATED = 'TOON_IMAGES_UPDATED'

export const GET_TOON_IMAGES_DB = 'GET_TOON_IMAGES_DB'
